[project]
name = "urlshotener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.129.0",
    "ipython>=9.10.0",
    "pandas>=3.0.1",
    "sqlalchemy>=2.0.46",
    "uvicorn>=0.41.0",
]
